plot 'sna005.1' with lines
pause -1
plot 'sna006.1' with lines
pause -1
plot 'sna007.1' with lines
pause -1
plot 'sna008.1' with lines
pause -1
plot 'sna009.1' with lines
pause -1
plot 'sna010.1' with lines
pause -1
plot 'sna011.1' with lines
pause -1
plot 'sna012.1' with lines
pause -1
plot 'sna013.1' with lines
pause -1
plot 'sna014.1' with lines
pause -1
plot 'sna015.1' with lines
pause -1
plot 'sna016.1' with lines
pause -1
plot 'sna017.1' with lines
pause -1
plot 'sna018.1' with lines

