plot 'sna019.1' with lines
pause -1
plot 'sna020.1' with lines
pause -1
plot 'sna021.1' with lines
pause -1
plot 'sna022.1' with lines
pause -1
plot 'sna023.1' with lines
pause -1
plot 'sna024.1' with lines
pause -1
plot 'sna025.1' with lines
pause -1
plot 'sna025b.1' with lines
pause -1
plot 'sna026.1' with lines
pause -1
plot 'sna027.1' with lines
pause -1
plot 'sna028.1' with lines
pause -1
plot 'sna029.1' with lines
pause -1
