* Overview
* Simulation
** Experiment 1
A very simple start to the simulation. Using the default values for the searcher:
 - average turn 20
 - std dev of turn 5

Change the number of entities per patch whilst keeping the number of patches constant.
Increase the values to see if there is a value that give an optimum number of entities caught.   

** Experiment ??
How does the rate of encounter for a searcher change as the average angle turned by the searcher varies. Let angle turned be a normal distribution with set SD. As items are encountered they are removed. The distribution of items ranges from random to aggregated.

Let mean angle turned start at 10 and increment at 10 steps, ie 20, 30, 40 until 90.

Let the SD be 0.1 of the angle turned?? So the greater the mean turn, the higher the SD and more variability in the turns. Does this make sense, should the SD be standard across all. So ther are two experiments:
one with SD a ratio of the mean turn, the other a set SD.

* Reference
** Kitchener
Kitchener Jennifer, A. The Evolution of Predator Prey Behaviour: Naticid Gastropos and Their Molluscan Prey in Evolution of Animal Behaviour: Paleontological and Field Approaches eds Nitecki, Matthew. H., Kitchell, Jennifer, A

** Green, R.F.
   [[http://www.d.umn.edu/~rgreen/][List of Greens papers]]
   [[http://www.d.umn.edu/~rgreen/Summary.pdf][Greens summary of his Optimal Foraging papers]]

** Journals
   [http://www.movementecologyjournal.com/]


