plot 'sna059.1' with lines
pause -1
plot 'sna060.1' with lines
pause -1
plot 'sna061.1' with lines
pause -1
plot 'sna062.1' with lines
pause -1
plot 'sna063.1' with lines
pause -1
plot 'sna064.1' with lines
pause -1
plot 'sna065.1' with lines
pause -1
plot 'sna066.1' with lines
pause -1
plot 'sna067.1' with lines
pause -1
plot 'sna068.1' with lines
pause -1
plot 'sna069.1' with lines
pause -1
plot 'sna070.1' with lines
pause -1
plot 'sna071.1' with lines
pause -1
plot 'sna072.1' with lines
pause -1
plot 'sna073.1' with lines
pause -1
plot 'sna074.1' with lines
pause -1
plot 'sna075.1' with lines
pause -1
plot 'sna076.1' with lines
pause -1
plot 'sna078.1' with lines
pause -1
plot 'sna079.1' with lines
pause -1
plot 'sna080.1' with lines
pause -1
plot 'sna081.1' with lines
pause -1
plot 'sna082.1' with lines
pause -1
plot 'sna083.1' with lines
pause -1
plot 'sna084.1' with lines
pause -1
plot 'sna085.1' with lines
pause -1
plot 'sna086.1' with lines
pause -1
plot 'sna087.1' with lines
pause -1
plot 'sna088.1' with lines
pause -1
plot 'sna089.1' with lines
pause -1
plot 'sna090.1' with lines
pause -1
plot 'sna091.1' with lines
pause -1
plot 'sna092.1' with lines
pause -1
plot 'sna093.1' with lines
pause -1
plot 'sna094.1' with lines
pause -1
plot 'sna095.1' with lines
pause -1
plot 'sna096.1' with lines
pause -1
plot 'sna097.1' with lines
pause -1
